version: '3.4'

services:
  jira:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"
    ports:
      - "${HTTP_PORT:-8080:8080}"
    volumes:
      - ./data:/var/atlassian/application-data/jira
    environment:
      TZ: 'Asia/Shanghai'
      JVM_MINIMUM_MEMORY: 384m
      JVM_MAXIMUM_MEMORY: 2g
      JVM_CODE_CACHE_ARGS: '-XX:InitialCodeCacheSize=512m -XX:ReservedCodeCacheSize=1g'


